spring:
  profiles:
    active: local
  batch:
    initialize-schema: always
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: batch_demo
    password: batch_demo

---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/batch_demo

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://batch-demo.crtxqczk1noq.ap-northeast-2.rds.amazonaws.com/batch_demo
